Milestone 5
verissimohenry/Bookstore-CMS pull request #5
Opened 2021-09-11 11:25 UTC by verissimohenry

In this milestone, I followed the provided design specs to build a UI for your app.

2021-09-11 13:16 UTC, rindrajosia requested changes
Hi, 

Good job so far!
There are some issues to revise before continuing to the next project but hang in there and read the comments below with care. You can do it! :muscle:


## Required Changes ♻️

- [ ] Files not related to the project should not be committed and added to .gitignore (e.g. .vscode)([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] all element in the design, features that haven’t been implemented yet should be added as a placeholder and does not need to be implemented ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone5/designAllElementAsPlaceholder.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/45791599/)).
![3](https://user-images.githubusercontent.com/58552748/132948784-f946e89e-ca57-48e3-a199-260bb272e0dc.png)

- [ ] I was not able to check how each book will be displayed in your APP because no default list of books is shown. In addition, I was not able to add new book. It will be nice if you fix it and implement all the features and styles related to it.
- [ ] Styling should be **EXACTLY** the same as the one provided in the designs ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone5/exactlySameAsDesign.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/45791599/)) (eg: font-color, font-size, font-weight, layout, margin and padding between each elements, ...)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-09-11 13:16 UTC, rindrajosia commented on src/components/Book.js
>  /* eslint-disable react/prop-types */
- [x] [REQUIRED] Please don't disable react/prop-types  validation. Keep in mind that PropTypes are a mechanism to ensure that components use the correct data type and pass the right data, and that components use the right type of props, and that receiving components receive the right type of props.

2021-09-11 13:16 UTC, rindrajosia commented on src/index.css
> +  align-items: center;
- [ ] [REQUIRED] In the stylesheets of the app, make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2021-09-11 13:16 UTC, rindrajosia commented on src/index.css
> +  display: flex;
- [ ] [REQUIRED] In the stylesheets of the app, make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2021-09-11 13:16 UTC, rindrajosia commented on src/index.css
> +  align-items: center;
- [ ] [REQUIRED] In the stylesheets of the app, make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2021-09-11 18:00 UTC, oloomoses requested changes
Hi @verissimohenry, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [ ] Kindly add `.vscode` folder into the `.gitignore` file and ensure that it is not uploaded into the repo as suggested in the previous review.
- [ ] Your design still doesn't match the given one. Kindly check the screenshot and ensure that the avatar, item container, and add_book button align
![ddd](https://user-images.githubusercontent.com/20245164/132956962-656b88a7-c72d-4287-9872-bbcff4a262ea.jpg)
 
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-13 12:58 UTC, george-shammar requested changes
Hi @verissimohenry , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-09-13 12:58 UTC, george-shammar commented on .gitignore
- [ ] Although you've added `.vscode` to `.gitignore`, it is still visible on github. You need to manually remove it. Please, let's remove the file from the repo as mentioned in the previous reviews. :pray:

2021-09-13 12:58 UTC, george-shammar commented on README.md
>  In the project directory, you can run:
[OPTIONAL]

- Please include the live version of your application in your README.

2021-09-13 13:48 UTC, george-shammar approved these changes
Hi @verissimohenry , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-09-13 14:07 UTC, merged